// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLb4ZxcXVEsaE-FqmUJa5A9w8Bg7f0t0',
    appId: '1:301580008305:web:7861fd906d6838c064d4d0',
    messagingSenderId: '301580008305',
    projectId: 'chat-app-232fe',
    authDomain: 'chat-app-232fe.firebaseapp.com',
    storageBucket: 'chat-app-232fe.appspot.com',
    measurementId: 'G-26H4BKJ4P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GObEKVliZheC40ZxMcbK2ACzfMJZ9iQ',
    appId: '1:301580008305:android:f8b5945ddbf60db664d4d0',
    messagingSenderId: '301580008305',
    projectId: 'chat-app-232fe',
    storageBucket: 'chat-app-232fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANybcs7Qe9XKzrb0Xi7sz_DNYDbK4QcQs',
    appId: '1:301580008305:ios:44d49deba124c1c564d4d0',
    messagingSenderId: '301580008305',
    projectId: 'chat-app-232fe',
    storageBucket: 'chat-app-232fe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANybcs7Qe9XKzrb0Xi7sz_DNYDbK4QcQs',
    appId: '1:301580008305:ios:44d49deba124c1c564d4d0',
    messagingSenderId: '301580008305',
    projectId: 'chat-app-232fe',
    storageBucket: 'chat-app-232fe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLb4ZxcXVEsaE-FqmUJa5A9w8Bg7f0t0',
    appId: '1:301580008305:web:af44fd927109e93464d4d0',
    messagingSenderId: '301580008305',
    projectId: 'chat-app-232fe',
    authDomain: 'chat-app-232fe.firebaseapp.com',
    storageBucket: 'chat-app-232fe.appspot.com',
    measurementId: 'G-E96131BJT1',
  );
}
